proxy:
  title: Jonah Ventures shiny swarm
  port: 8080 # use Port 8080 for ShinyProxy
  
  container-wait-time: 30000 # how long should we wait for the container to spin up (30s as default as this is enough for our Shiny apps)
  heartbeat-rate: 10000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 60000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)

  #### Set Up Usage Statistics Monitoring
  # usage-stats-url: http://influxdb:8086/write?db=shinyproxy_usagestats # use InfluxDB to store usage statistics; can be in a different server
  # usage-stats-username: xxxx # influxdb username if needed
  # usage-stats-password: xxxx # influxdb password if needed

  #### OpenID Connect Authentication ####
  authentication: openid # use openid auth framework
  openid:
    roles-claim: cognito:groups # use the groups value passed by AWS cognito to identify user groups
    auth-url: https://shinyproxy-jonahdna.auth.us-east-1.amazoncognito.com/oauth2/authorize
    token-url: https://shinyproxy-jonahdna.auth.us-east-1.amazoncognito.com/oauth2/token
    jwks-url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DF4g0mr7n/.well-known/jwks.json
    logout-url: https://shinyproxy-jonahdna.auth.us-east-1.amazoncognito.com/logout?client_id=405avc5g9c9g14f6pteo9b085r&logout_uri=https://shinyproxy.jonahdna.com
    client-id: 405avc5g9c9g14f6pteo9b085r
    client-secret: 1p3vm3l8adsr7gr8hhse52bl2na7eagr4634ccfsp0opt2oc6v7q
  
  #### Simple Authentication (for demo only, don't use in production) ####
  #authentication: simple
  #admin-groups: admins
  #users:
  #- name: admin
  #  password: admin
  #  groups: admins
  #- name: test
  #  password: test
  #  groups: admins
  
  # Set the container backend: The container-backend can be one of docker (default), docker-swarm or kubernetes
  container-backend: docker-swarm
  
  docker:
      internal-networking: true
  
  # Below is a list of Shiny apps and their config
  specs:
    - id: jonah-lims
      display-name: Jonah LIMS
      container-cmd: ["R", "-e", "options('shiny.port'=3838,shiny.host='0.0.0.0');jonah.lims::run_app()"]
      container-image: drleopold/jonah-lims # this need to be replaced with your own Shiny app in production
      access-groups: admins # give specific access right to a group
      container-network: sp-net

server:
  useForwardHeaders: true # this is very important to make the AWS Cognito auth works

logging:
  file:
    shinyproxy.log